### PR TITLE
Tweak

### PR DESCRIPTION
**Pull request by raxo2222**

### CODE REVIEW

**Comment by MattOttawa** [comment]
does that file work?

**Comment by raxo2222** [comment]
> 
> 
> does that file work?
Yeah, it worked when it was first used

**Comment by raxo2222** [comment]
Also this crashes bit later
Attempting to lint modules for python version 3
Installing pylint for python 3
Linting python 3 modules
Traceback (most recent call last):
  File "Tools/Lint/pylint.py", line 130, in <module>
    _main()
  File "Tools/Lint/pylint.py", line 36, in _main
    modules=_python_modules_for_python_version(python_version),
  File "Tools/Lint/pylint.py", line 124, in _lint_modules_for_python_version
    *[path.resolve() for path in modules],
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)

Also no idea how to fix remaining warnings

**Comment by MattOttawa** [comment]
I'm not 100% sure how to fix either.
One thing is you give it 'CIV4TechInfos.xml' as a path to a file. I think you need to make that a full path.

**Pull request merged**
