### PR TITLE
switch long long back to int for CyPlayer::changeGold to fix bug reported by jatkinson

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by Toffer90** [comment]
This is the wrong way to fix the bug reported by jatkinson.
Python is giving a float, so long long and int are both equally wrong in that sense.
The bug is rather in the python code that delivers a float when a long long is expected.

**Comment by Toffer90** [comment]
I fixed a couple changeGold spots in python that delivered float a couple days ago in commit 8b42e3a1226ea20cc3cb8626c22bda354ec5368f

**Comment by MattOttawa** [comment]
You sure you want that a long long anyways? int should be big enough.

**Comment by Toffer90** [comment]
The set function should be capable of setting any valid value.
And looking into it, the bug jatkinson had is already fixed on git, it is one of the spots I fixed.

**Pull request closed without merging**
