### PR TITLE
switched array to vector

### PR DESCRIPTION
**Pull request by MattOttawa**
just gotta do xml I think.

### CODE REVIEW

**Comment by MattOttawa** [comment]
too much xml

**Comment by Toffer90** [comment]
I can do the xml here later today.

**Comment by Toffer90** [comment]
Hmm, Blaze's recent unit xml file splitting broke the xml work here.
If you revert the xml part I contributed I'll redo the xml convertion.

**Comment by dzfischer** [comment]
Whoops.
Looks like the XML half of things changed is just a simple find-and-replace though, right?

**Comment by Toffer90** [comment]
It is, 
Takes about 2 minutes to redo the xml work.

**Pull request closed without merging**
