### PR TITLE
pr318-merge revised

### PR DESCRIPTION
**Pull request by MattOttawa**
Added const to map functions.
Removed unused code in CvGlobals.

### CODE REVIEW

**Comment by MattOttawa** [comment]
yup. I don't understand github yet.

**Comment by billw2012** [comment]
What do you not understand here?

**Comment by billw2012** [comment]
If you are trying to make separate PRs then you need to use separate source branches. i.e. make a new branch on your fork called whatever the PR is for, then make the PR from that branch to our master.

**Comment by billw2012** [comment]
So should I review this PR or not? I spent an hour reviewing the last one then you deleted it, so this time I'm going to wait for you to say it is definitely ready!

**Comment by raxo2222** [comment]
Useable Mountains options is now hidden and enabled by default, as Thunderbrd requested some time ago.

**Comment by MattOttawa** [comment]
I no touch

**Comment by billw2012** [comment]
I merged this into a new branch and fixed up one place were you reverted newer changes.
It crashes as soon as I play it in Assert mode due to you removing the checks for getHeadUnit() being null in a CvSelectionGroup. It is perfectly possible for CvSelectionGroup to be empty.
You need to correctly test your changes in game in the Assert build thoroughly.
https://github.com/caveman2cosmos/Caveman2Cosmos/tree/pr318-merge

**Comment by billw2012** [comment]
Also to be clear do NOT close this PR! Instead you should merge from the new branch back to your master, then test and fix up in master and commit the fixes.
That way the parts I will be able to see what changes you made and review just those.

**Comment by MattOttawa** [comment]
Ran out of patience, which is rare for me. Thanks for the help so far bill.

**Pull request merged**
