### PR TITLE
const2

### PR DESCRIPTION
**Pull request by MattOttawa**
Added const to functions returning a struct.

### CODE REVIEW

**Comment by MattOttawa** [comment]
conclicts

**Comment by Toffer90** [comment]
You have my permission to merge this yourself If it's ready to be merged.

We trust your judgement, and that you will voice concern if you are unsure about your own PR and want someone to review it.

If a PR change gameplay in a significant way then it's more important to get an OK signals from the other team members.

**Comment by MattOttawa** [comment]
Not changing gameplay is always number one goal so far.
I actually don't see a way to merge this, or a notification of any kind.

**Comment by Toffer90** [comment]
Did you accept the member invite I sent you?
You are still not on the member list. Perhaps it takes a bit time after you accept before you are added. . .

**Pull request merged**
