### PR TITLE
fix(wonder prereqs): mostly animal trainer+heritages and units, plus log roller

### PR DESCRIPTION
**Pull request by dzfischer**
This should be it for matching the alternate history animal trainer wonders and units with each other (plus the log roller because it annoyed me once), though the entire animal trainer module really needs a polishing pass or two; it's all over the place, both in coding practices and pedia text

### CODE REVIEW

**Comment by raxo2222** [comment]
I checked it, looks good enough, but things should require myth EFFECTS, not myths themselves.
Myth effects are created everywhere in empire, while myth is in one city only. 
Myth and stories effect makes those myth and stories pseudonational wonders.

**Comment by dzfischer** [comment]
The animal trainers all required myths instead of myth effects with the exception of the bear trainer, so that should be the only one I switched from myth effect to straight myth, to align with the other trainers. Easy enough to switch back if you want?

**Comment by raxo2222** [comment]
Well I'm replacing myth with myth effect requirements now, so no need for this.

**Comment by raxo2222** [comment]
It appears only megafauna domestication buildings weren't using myth effects lol.

**Comment by dzfischer** [comment]
Yeah, that was the feeling I got. It kinda made sense in some regards, as in 'Only where the myth itself was born, could a great trainer rise to the occasion!' but, either way works fine

**Comment by raxo2222** [comment]
Megafauna domestication is not too far from Tribalism, so you will have only couple of cities anyway unless you go all out of war on barbarian cities and neighbour civs.
Also myth effects appear instantly anywhere, so there is no reason to force those buildings to single city ;)

**Pull request merged**
