### PR TITLE
Excile exile typo (untested)

### PR DESCRIPTION
**Pull request by paulcobbaut**
Changing 15 files to correct the "Excile-Exile" typo.

Some .cpp files are changed, but I do not have a development environment setup to compile C2C. So this is untested and may break...

Should I hold off such pull requests until I can compile C2C myself?

### CODE REVIEW

**Comment by raxo2222** [comment]
If you set this mod to be gameplay mod (that is if you followed instructions to setting up it), then DLL will autocompile every time you do changes to cpp files.
Tools folder also have makedll files

**Comment by Toffer90** [comment]
The PR itself does a compile test, and it compiled successfully.

The third one there is dll compilation test:
image

**Comment by Toffer90** [comment]
Only problem is that this:
image
breaks save compatibility.

**Comment by Toffer90** [comment]
> Only problem is that this: image breaks save compatibility.

Most practical solution is to simply not rename this one variable.

**Comment by paulcobbaut** [comment]
Thanks for all the replies. I will update this later.

**Pull request closed without merging**
