### PR TITLE
civ mega pack

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by raxo2222** [comment]
I think you should start with original one https://forums.civfanatics.com/threads/c2c-civilizations-megapack.538110/

**Comment by Toffer90** [comment]
We shouldn't have this many civs in core, it clutters the civ selection list, increases launch time (especially the leaderhead art); it is just more practical as a modmod.

**Comment by raxo2222** [comment]
He could be just fixing it on github

**Comment by Toffer90** [comment]
> He could be just fixing it on github

Then why make a pull request to master?

**Comment by MattOttawa** [comment]
miccal2000 is sayin xml validator won't work for linux. This will work on linux.

**Comment by raxo2222** [comment]
It could be put to Unloaded Modules too

**Comment by MattOttawa** [comment]
Based on public opinion, I like if someone fixes this, then adding in to unloaded modules makes sense.

**Comment by Toffer90** [comment]
All the art files would still be loaded though. Would be about 1 MB per 10 leaders.
How many civs are in this pack? I'm guessing most of them have two leaders each.

**Pull request closed without merging**
