### PR TITLE
Merged CvBug into CvGlobals

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by billw2012** [comment]
Why is this an improvement? Chucking more unrelated stuff in a global mega object is not better as far as I can see, its worse. I'm willing to be convinced though.

**Comment by MattOttawa** [comment]
CvBug.h:
void logMsg(const char* format, ...);  // Matt: don't need

bool isBug();  // Matt: already a version of this in CvGlobals that is used. 
void setIsBug(bool bIsBug); // Matt: already a version of this in CvGlobals that is used. 

bool getDefineBOOL(const char* xmlKey, bool bDefault = false); // Matt: already a version of this in CvGlobals.
int getDefineINT(const char* xmlKey, int iDefault = 0); // Matt: already a version of this in CvGlobals.
float getDefineFLOAT(const char* xmlKey, float fDefault); // Matt: already a version of this in CvGlobals.
const char * getDefineSTRING(const char* xmlKey, const char * szDefault); // Matt: already a version of this in CvGlobals.

bool getBugOptionBOOL(const char* id, bool bDefault = true, const char* xmlKey = NULL);
int getBugOptionINT(const char* id, int iDefault = 0, const char* xmlKey = NULL);

Leaves 2 calls to python as unrelated stuff.

**Comment by MattOttawa** [comment]
I would like to remove unused python calls.
I'm not sure if everyone is on board with that tho. 
If i can, i'll be able to get rid of like 30 getters and 30 ints from CvGlobals.

**Comment by MattOttawa** [comment]
Also Granular Callback Controller thing can be removed too from CvGlobals if no1 minds.

**Comment by MattOttawa** [comment]
This stuff at the end of CvGlobals.h is hardly used if at all.
#define NUM_DIRECTION_TYPES (GC.getNumDirections())
#define NUM_GAMEOPTION_TYPES (GC.getNumGameOptions())
#define NUM_MPOPTION_TYPES (GC.getNumMPOptions())
#define NUM_SPECIALOPTION_TYPES (GC.getNumSpecialOptions())
#define NUM_GRAPHICOPTION_TYPES (GC.getNumGraphicOptions())
#define NUM_TRADEABLE_ITEMS (GC.getNumTradeableItems())
#define NUM_BASIC_ITEMS (GC.getNumBasicItems())
#define NUM_TRADEABLE_HEADINGS (GC.getNumTradeableHeadings())
#define NUM_COMMAND_TYPES (GC.getNumCommandInfos())
#define NUM_CONTROL_TYPES (GC.getNumControlInfos())
#define NUM_PLAYEROPTION_TYPES (GC.getNumPlayerOptionInfos())
#define MAX_NUM_SYMBOLS (GC.getMaxNumSymbols())
#define NUM_GRAPHICLEVELS (GC.getNumGraphicLevels())
#define NUM_GLOBE_LAYER_TYPES (GC.getNumGlobeLayers())

**Comment by MattOttawa** [comment]
Also those 2 getBugOption() calls can be merged into 1. it ends up running the same code shortly after hitting the python.

**Comment by Toffer90** [comment]
> I would like to remove unused python calls.
> I'm not sure if everyone is on board with that tho.
> If i can, i'll be able to get rid of like 30 getters and 30 ints from CvGlobals.

This should not be done wholesale, each case should be evaluated as for their future usefulness.

> Also Granular Callback Controller thing can be removed too from CvGlobals if no1 minds.

This I would not mind, I've earlier expressed that I think these should be removed.

**Comment by MattOttawa** [comment]
I'll start a list of the python calls I think are dumb.

**Comment by Toffer90** [comment]
> I'll start a list of the python calls I think are dumb.

Great, but let's discuss it in a new forum thread instead of in this clunky environment.

**Comment by billw2012** [comment]
Is this complete? There was a bunch of discussion on here, is there anything remaining to resolve or is this good to go?

**Comment by MattOttawa** [comment]
This is complete. Only unresolved thing may be your first comment.

**Comment by MattOttawa** [comment]
Fixed conflicts multiple times and there's more.  Trying to contribute to this mod has made me mad for 2 months. Not sure what I'm gonna do.

**Comment by Thunderbrd** [comment]
I kinda mentioned to Bill that I didn't want to have to review efforts to contribute like this and in the process of setting all this up he said it wasn't going to be a pain to do it, which I assumed he meant he'd be happy to review them for us.  He's been a bit distracted of late, as have I.  I don't feel terribly qualified to comment on some of the projects you get into as they are often about just improving the programming in ways I don't usually see why we need to in these cases.  I may have to just give you direct access as long as you're then willing to take responsibility for bugfixes that become necessary as a result.  Sorry if it feels like your work has been unappreciated - that's not my intent at all.

**Comment by Toffer90** [comment]
Yeah, you gotta communicate a bit better about what your PR does and whether they are finished or not, or have issues or not that you know of. 
Nag us a bit on discord if you feel left out or forgotten. ^^

Either that or we should get you on the modding team proper (off the fork) so you don't have to PR every single little thing you do, but can commit them directly on master yourself.

**Pull request closed without merging**
