### PR TITLE
Removed redundant pop destroy entries, very tall grass destroys at pop=3

### PR DESCRIPTION
**Pull request by dzfischer**

### CODE REVIEW

**Comment by MattOttawa** [comment]
This can be merged right? Was mentioned on the forums I think.
I'll probably merge any pull requests that get no comments after a couple days.
Unless someone wants to be in charge of this guys pull requests.

**Comment by dzfischer** [comment]
Ready to merge; I just like to leave PRs up for a few days in case someone has objections. Ones that aren't ready will be drafts, like the tech diffusion one.

**Comment by MattOttawa** [comment]
Yes, Blazenclaw on forums. You been around a while.
More people modding = more variety of updates. I like that.

**Comment by MattOttawa** [comment]
This comment didn't go to discord:

This can be merged right? Was mentioned on the forums I think.
I'll probably merge any pull requests that get no comments after a couple days.
Unless someone wants to be in charge of this guys pull requests.

**Comment by MattOttawa** [comment]
Nevermind, I didn't realize you are on github team.

**Pull request merged**
