### PR TITLE
Tech names fixed

### PR DESCRIPTION
**Pull request by GreatCoffers**
I've done my changes and I have discussed my renamings on Github. I just want it to be evaluated for next release if wanted or possible.

### CODE REVIEW

**Comment by billw2012** [comment]
Why did you make a PR from release into master?

**Comment by GreatCoffers** [comment]
> Why did you make a PR from release into master?

I have no real idea what I'm doing.

**Comment by billw2012** [comment]
Well if you don't know then ask!

**Comment by billw2012** [comment]
It wasn't meant to sound harsh by the way, I just mean you shouldn't be worried asking about anything you don't know, not that you messed anything up here.

**Pull request closed without merging**
