### PR TITLE
Promotionline cleanup

### PR DESCRIPTION
**Pull request by raxo2222**
I cleaned up promotions and promotionlines.

### CODE REVIEW

**Comment by raxo2222** [comment]
I'm not sure of correctness of those changes, so I need assurance,

**Comment by flabbert** [comment]
TBH, with these kinds of promotions i am not too scared, worst thing that happens is that some units lose promotions, and we can revert if it all goes to hell.

**Comment by raxo2222** [comment]
Promotions without defined unit combats:
Starsigns - Aquarius, Aries, Cancer, Capricorn, Gemini, Leo, Libra, Pisces, Sagittarius, Taurus, Virgo

General promos:
Bushman, Chain Shot, Cliff Walker, Copper Plating, Crowded, Freedom Fighter, Grape Shot, Green Warden, Hunter Great, Imperial Guard, Mega Beam, Sand Devil, Scorpio, Segmented Armor, Tribal Guardian, Winter Born, Wootz Steel

Size and Quality promos also doesn't have defined unitcombats.

If its given by event, building, or is free promo for unit, then invalid unit may get it.

**Comment by raxo2222** [comment]
Promotions without defined unit combats:
Starsigns - Aquarius, Aries, Cancer, Capricorn, Gemini, Leo, Libra, Pisces, Sagittarius, Taurus, Virgo

General promos:
Bushman, Chain Shot, Cliff Walker, Copper Plating, Crowded, Freedom Fighter, Grape Shot, Green Warden, Hunter Great, Imperial Guard, Mega Beam, Sand Devil, Scorpio, Segmented Armor, Tribal Guardian, Winter Born, Wootz Steel

Size and Quality promos also doesn't have defined unitcombats.

If its given by event, building, or is free promo for unit, then invalid unit may get it.

**Comment by flabbert** [comment]
wootz steel is an event promotion. Imperial guard i am pretty sure comes from that world wonder spawned unit (the crusades wonder?)

**Comment by raxo2222** [comment]
> 
> 
> wootz steel is an event promotion. Imperial guard i am pretty sure comes from that world wonder spawned unit (the crusades wonder?)
I know that some are from events, but they all could have defined unit combats, even if it covers ALL units.

I can list those promos exactly:
PROMOTION_BUSHMAN - Militia promotion
PROMOTION_CHAIN_SHOT - Given to some (wooden) ships by event
PROMOTION_CLIFF_WALKER - Militia promotion
PROMOTION_COPPER_PLATING - Given to all wooden ships by event 
Crowded - Removed
PROMOTION_FREEDOM_FIGHTER - Given directly to Partisan unit.
PROMOTION_GRAPE_SHOT - Given to some types of cannons by event
PROMOTION_GREEN_WARDEN - Militia promotion
PROMOTION_HUNTER_GREAT - Given to some hunters by event in module
PROMOTION_IMPERIAL_GUARD - Given directly to Imperial Guard units
PROMOTION_MEGA_BEAM - Regular promo on top of multiple promotionlines
PROMOTION_SAND_DEVIL - Militia promotion
PROMOTION_SEGMENTED_ARMOR - Given to all melee units by event
PROMOTION_GUARDIAN_TRIBAL - Given to starter settler to make defense unit for first city.
PROMOTION_WINTERBORN - Militia promotion
PROMOTION_WINTERBORN - Given to multiple unitcombats by event

**Pull request merged**
