### PR TITLE
Improvements that breaks saves

### PR DESCRIPTION
**Pull request by Toffer90**

### CODE REVIEW

**Comment by raxo2222** [comment]
Unit Classes can be nuked too.

**Comment by Toffer90** [comment]
I think this should be merged with master sooner rather than later, what do you think?

It would get everyone together in focusing on removing unit-/building-classes.

**Comment by raxo2222** [comment]
> 
> 
> I think this should be merged with master sooner rather than later, what do you think?
> 
> It would get everyone together in focusing on removing unit-/building-classes.

I think you need to restore TECH_DUMMY first if it was used by code at all - those promotions could be rewards from events or so.
Another reason for that could be simply decluttering FUTURE_TECH.

**Comment by raxo2222** [comment]
It seems like you changed my space map for testing purposes, you can replace it with version from Master when you merge it.

**Comment by Toffer90** [comment]
> It seems like you changed my space map for testing purposes, you can replace it with version from Master when you merge it.

Yeah, it was a wild edit that I'm aware of, it was code that edited the file, not me manually.

**Comment by Toffer90** [comment]
> I think this should be merged with master sooner rather than later, what do you think?

@billw2012 @Thunderbrd @MattOttawa

**Comment by MattOttawa** [comment]
This branch is huge, raxo's is even bigger, and I just posted another big pr.
If the team is not ready to break saves yet then maybe we could at least merge the prs together. 
Then any future prs that are large, or break saves can be branched off of that branch.

That, or merge this into master.
Waiting too long is worst option I think.

**Comment by Toffer90** [comment]
> This branch is huge, raxo's is even bigger, and I just posted another big pr.
> If the team is not ready to break saves yet then maybe we could at least merge the prs together.
> Then any future prs that are large, or break saves can be branched off of that branch.
> 
> That, or merge this into master.
> Waiting too long is worst option I think.

If you have done some basic in game testing on your INLINE removal PR then we should merge that one to master right away at least.

**Comment by MattOttawa** [comment]
ya, I tested it.

**Comment by MattOttawa** [comment]
Have you started fixing these conflicts? I can do it for you if you want.

**Comment by Toffer90** [comment]
> Have you started fixing these conflicts? I can do it for you if you want.

I've not started yet, do you really want to though?

**Comment by MattOttawa** [comment]
Ya, I got it.

**Comment by Toffer90** [comment]
> Ya, I got it.

Thanks, I was thinking the easiest way was to just let this branch win evey conflict and then open the file in notepad and search for "INLINE" and replace the few stragglers after the merge with the simpler name you replaced them with in your branch.

**Comment by MattOttawa** [comment]
ya, that's what I did except one conflict at a time. Didn't even bother reading the master branch version.

**Comment by MattOttawa** [comment]
I thought i could make a pull request to your pr, but it seems to go to master as usual. 
I think best I can do is make regular pr and you can download and remake pr if you wanna keep goin. 
I don't really know...

**Comment by Toffer90** [comment]
> I thought i could make a pull request to your pr, but it seems to go to master as usual.
> I think best I can do is make regular pr and you can download and remake pr if you wanna keep goin.
> I don't really know...

Looked correct to me.

PR: merged master branch #443
	MattOttawa wants to merge 6 commits into caveman2cosmos:breakSavesToffer from MattOttawa:breakSavesToffer-merged

**Comment by Toffer90** [comment]
> I think this should be merged with master sooner rather than later, what do you think?

Since no one is objecting clearly I'm making the call to merge this.

I'll do so in 2 hours unless someone objects before then, this will break saves on master.

@billw2012 @Thunderbrd

**Comment by Thunderbrd** [comment]
I don't like having to respond here because this is the one place I struggle to respond when on my phone.  I did respond on discord in response to this statement as it was reported.

To give more details, I would've hoped we'd bundle in a lot more necessity into any save breakage than this.  Further, if we start this process now, it's going to be half a year or more of constantly breaking saves.  My own unit review might as well break them, even if it won't technically do so.  The removal of unit and building classes certainly would.

I know what it's like to want to get your work in place though and we did just release v40.1 in prep for breakage.  I won't stand in the way but I have reservations in feeling like we are breaking saves over trivial things right now and its going to force us to work on other things that break saves to try to get it all done in as small an amount of time as possible, and right now I don't see it being a very small period of time at all.  So for the next half a year to a year we'll be breaking saves regularly and I hope we can survive that.

**Pull request merged**
