### PR TITLE
French Translation - Pass 2 (merged with last master branch)

### PR DESCRIPTION
**Pull request by Calvitix**
Correction of mismatch on Global and Promotion Files, as I didn't update last merges.
I Hope all is corrected now.
Sorry again for the inconvenients

### CODE REVIEW

**Comment by raxo2222** [comment]
There are conflicts, because I fixed your reverts after merging it.

**Comment by Calvitix** [comment]
Meanwhile, I think I added some other modifications on those files.
I Took the master files from 5 hours ago, and merged the modifs with mine.

How can we going on ? It means that I have to rollback the Pull request ? 
I think I can't resolve the conflicts, as I don't have write access on master branch.

Sorry again for all that additionnal work. I think now I'm done with all translations in those 2 files, and won't update them for a while (until there are other updates).

**Comment by raxo2222** [comment]
I fixed those conflicts and now merged your changes.

**Comment by Calvitix** [comment]
ok, thanks a lot. I just found a bugI thought was remonved : 
 in Global file, line 14163,  remove the <F>

**Comment by raxo2222** [comment]
Notepad notified me, that something was amiss with tag, and validator located it exactly :p

**Comment by Calvitix** [comment]
Great. I'll continue working on the translation. Thanks again.

**Pull request merged**
