### PR TITLE
Tweaks to Limited Religion and global techs

### PR DESCRIPTION
**Pull request by Toffer90**
@raxo, please check with the prepared save you had that global techs act as they should when invented in regards to other players tech queue.

The limited religion changes should wait until after v40.1 release in any case as they are more extensive. It address the oversight of allowing a player to hoard all the religious techs to deny other players the ability to found religions even though the hoarding player won't found religions after the first. Since the rel. techs can only be invented by one player it makes it so that a player that has founded a religion cannot invent more religious techs.

### CODE REVIEW

**Comment by Toffer90** [comment]
Most of the changes are related to limited religions, the actual fix for global techs lingering in the players tech queue after another player invented it is only a couple of code lines in the same code section and can easily be cherrypicked to master branch without bringing anything else along.

The limited religion changes should wait until after v40.1 release in any case as they are more extensive. It address the oversight of allowing a player to hoard all the religious techs to deny other players the ability to found religions even though the hoarding player won't found religions after the first. Since the rel. techs can only be invented by one player it makes it so that a player that has founded a religion cannot invent more religious techs.

**Comment by Toffer90** [comment]
Oh, and the python stuff is just me cleaning out some unused and redundant stuff.

**Comment by raxo** [comment]
> @raxo, please check with the prepared save you had that global techs act as they should when invented in regards to other players tech queue.

@raxo2222 
My work is done here 👋

**Comment by Toffer90** [comment]
> My work is done here

Meaning?

**Comment by raxo2222** [comment]
> @raxo, please check with the prepared save you had that global techs act as they should when invented in regards to other players tech queue.
> 

It works now - got knocked off those two religious techs I had selected.
Researched one and got switched to Drying tech, as other religious tech was researched too.

**Comment by Toffer90** [comment]
This one needs a bit more testing before being merged.

**Pull request merged**
