### PR TITLE
Xml cleanup

### PR DESCRIPTION
**Pull request by raxo2222**
I cleaned up whitespaces and comments there

### CODE REVIEW

**Comment by Toffer90** [comment]
Things like this doesn't need to be a PR, could just push it straight to master, nothing controversial or potentially risky in white space changes.

**Comment by raxo2222** [comment]
Okay :)

**Comment by Toffer90** [comment]
Just don't do this kind of mass edit thing on the source files, they are usually structured with some redundant white spaces on purpose for readability reasons.

**Comment by raxo2222** [comment]
I know, did this only on XML files

**Pull request merged**
