### PR TITLE
removing unused functions from Cy files

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by MattOttawa** [comment]
#497

**Comment by Toffer90** [comment]
You've removed a function called from C2C_Pangaea.py
.def("setPlotTypes", &CyMapGenerator::setPlotTypes, "void (list lPlotTypes) - set plot types to the contents of the given list")

That's the only checked CyMapGenerator, all other removals in CyMapGenerator was ok.

**Comment by Toffer90** [comment]
.def("getNumBonusesOnLand", &CyMap::getNumBonusesOnLand, "int () - total bonuses on land plots")
.def("resetPathDistance", &CyMap::resetPathDistance, "void ()")
.def("calculatePathDistance", &CyMap::calculatePathDistance, "finds the shortest passable path between two CyPlots and returns its length, or returns -1 if no such path exists. Note: the path must be all-land or all-water")

Called from perfectWorld, perfectMongoose and world mapscript.

**Comment by MattOttawa** [comment]
I forgot to search map scripts.

**Pull request closed without merging**
