### PR TITLE
fix(Buildings): remove Tradition - Hunting as it isn't buildable

### PR DESCRIPTION
**Pull request by billw2012**

### CODE REVIEW

**Comment by billw2012** [comment]
@Thunderbrd can you just ok this before I commit it? Apparently this thing was showing up but there is no way to make it. Apparently abandoned part way through development, now just confusing people.

**Comment by Thunderbrd** [comment]
Are you sure it's not used in an event?

**Comment by billw2012** [comment]
I could not any reference to it anywhere in xml, python or dll, I will check again though.

**Comment by Thunderbrd** [comment]
The naming suggests it is supposed to be something a General or Great Hunter can make free to units OR that it comes from an event.  You pointed out that there are 2 versions and this one looks like a WIP that was never fully used.  If you've not been able to find any reference to it in any xml, python or dll file, then obviously, the other one is in use and this may just be one that was made and then forgotten so I'd be ok with removing it - it's on record and could be recovered.

**Pull request merged**
