### PR TITLE
[WIP] Removing INLINE from function names.

### PR DESCRIPTION
**Pull request by MattOttawa**
- work in progress.

I'm just changing names. Everything is still declared inline.

### CODE REVIEW

**Comment by billw2012** [comment]
Yeah nice, the INLINE versions are pointless, DLLExport functions [are inlinable](https://devblogs.microsoft.com/oldnewthing/?p=2123) so I don't know why someone wrote special INLINE versions anyway.

**Comment by MattOttawa** [comment]
So I can get rid of the "NonInl" functions I added right?

**Comment by billw2012** [comment]
Yep, only one function is necessary!

**Comment by billw2012** [comment]
Do you not build before committing? In debug it should only take < 30s to do iterative build usually.

**Comment by MattOttawa** [comment]
not with these draft ones. 
What's iterative build?
Here's from ust now.  It failed early.

1>--- Summary -----------------------------------------------------
1>                                 /----- Cache -----\
1>Build:          Seen    Built   Hit     Miss    Store   CPU
1> - Directory  : 2       2       -       -       -       0.063s
1> - Exec       : 1       1       -       -       -       10.036s
1> - File       : 1957    73      -       -       -       0.081s
1> - Object     : 63      9       -       -       -       1h:17m 58.185s
1> - Alias      : 1       0       -       -       -       0.000s
1> - Unity      : 1       1       -       -       -       4.783s
1> - Compiler   : 1       0       -       -       -       0.000s
1> - DLL        : 1       0       -       -       -       0.000s
1> - ObjectList : 1       0       -       -       -       0.000s
1>Cache:
1> - Hits       : 0 (0.0 %)
1> - Misses     : 0
1> - Stores     : 0
1>Time:
1> - Real       : 27m 30.273s
1> - Local CPU  : 1h:18m 13.148s (2.8:1)
1> - Remote CPU : 0.000s (0.0:1)
1>-----------------------------------------------------------------
1>FBuild : error : BUILD FAILED: Release-build
1>Time: 27m 34.089s
1>...Failed

**Comment by raxo2222** [comment]
Use compile tools

**Comment by billw2012** [comment]
What? If you are a coder just build in VS 2019, why would you use the batch file?! If you just want to test the compile then use Debug config.
This is a full rebuild in Debug:
image

**Comment by Thunderbrd** [comment]
Question about that - with the batch build, it will automatically place the dll in the assets - will it do that automatically when building in the VS environment?

**Comment by billw2012** [comment]
In both cases it will.

**Pull request closed without merging**
