### PR TITLE
deleted extra bool bEnforcesGameOption

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by MattOttawa** [comment]
#469

**Comment by Toffer90** [comment]
Good stuff. ^^

**Comment by MattOttawa** [comment]
copyNoneDefault() code I think by AIAndy should be able to replace all readpass2 and readpass2 right?
Might not be faster but it could be better in other ways.

**Comment by Toffer90** [comment]
I think copyNonDefault happens too early to replace readpass2, you would need a copyNonDefault2 to replace readpass2.

Not 100% sure on that though.

**Comment by MattOttawa** [comment]
I mixed up a bit. I meant copyNoneDefaultDelayedResolution and SetOptionalVectorWithDelayedResolution and other DelayedResolution code. (not copyNoneDefault)

**Comment by Toffer90** [comment]
> I mixed up a bit. I meant copyNoneDefaultDelayedResolution and SetOptionalVectorWithDelayedResolution and other DelayedResolution code. (not copyNoneDefault)

Okay, I don't know about that, you should PM AIAndy on cfc, or just experiment if that's more your style.

**Pull request merged**
