### PR TITLE
DrD_AVEL's russian translation PR

### PR DESCRIPTION
**Pull request by Toffer90**

### CODE REVIEW

**Comment by Toffer90** [comment]
This doesn't look like cyrillic to me...
image

**Comment by Toffer90** [comment]
Hmm, I found something that actually looked like cyrilic in 1 of the text xml files, so I tried reverting everything except this:
image

When I looked in-game for atompunk, all the russian text was empty spaces (no symbols) like so:
pedia
@drd-avel Have you or your buddy actually seen cyrilic text working in-game while doing this translation?

**Comment by Toffer90** [comment]
99% of all the translations look like this in the xml files:
image
Which for me looks the same in-game too...

**Comment by Toffer90** [comment]
Ok, drd_avel says it displays fine in-game for him, so it's probably just my windows/system that can't handle cyrilic symbols or something like that.

**Comment by SannitaSSJ** [comment]
> Ok, drd_avel says it displays fine in-game for him, so it's probably just my windows/system that can't handle cyrilic symbols or something like that.

I have the very same error... so we need to find a way to fix this.

**Comment by Toffer90** [comment]
> > Ok, drd_avel says it displays fine in-game for him, so it's probably just my windows/system that can't handle cyrilic symbols or something like that.
> 
> I have the very same error... so we need to find a way to fix this.

I don't think it's possible to fix it in the mod, pretty sure it's a system setup thing, e.g. needs to install russian language pack for windows, or something like that.

**Comment by SannitaSSJ** [comment]
This is not closed by the way, I tried to upload only a part of the edits, so the work is still not complete.

@drd-avel please check that the Russian version still displays as normal, and notice me any problem with that (or intervene directly on the branch).

**Comment by SannitaSSJ** [comment]
Alright, everything _should_ be ok now. I hope I imported back all of my typo corrections.

**Pull request merged**
