### PR TITLE
added back part I deleted a long time ago to fix ErmanTheTurk

### PR DESCRIPTION
**Pull request by MattOttawa**
doesn't work.

### CODE REVIEW

**Comment by Toffer90** [comment]
Cool, glad the error made sense to someone, it confused me.

**Comment by MattOttawa** [comment]
Na, it still crashes with this change.
This is old bug that nobody could fix.

**Comment by Toffer90** [comment]
The crash point does come later in the code with this change though.

**Comment by MattOttawa** [comment]
Ya it's probly debug code that never worked along with CvPlayer line 20219, and corrupted adjustment in FreeList files.
Something broken about save load for selection groups and all this code was added to fix after game is loaded, and it's still broken.

**Pull request closed without merging**
