### PR TITLE
removed building class from the dll

### PR DESCRIPTION
**Pull request by MattOttawa**
Don't remember what I done here. I need the xml done to see if I broke everything.
I do python next.

### CODE REVIEW

**Comment by raxo2222** [comment]
Game loaded just fine, but there was compile warning.
Also got python error in pedia when I clicked on tech, same with building and units.
Map generated properly, turns progresses fine.
I could even load that save.

**Comment by raxo2222** [comment]
Game loaded just fine, but there was compile warning.
Also got python error in pedia when I clicked on tech, same with building and units.
Map generated properly, turns progresses fine.
I could even load that save. There is lots of asserts though.

**Comment by MattOttawa** [comment]
I fixed the xml and added readpass2.
Just waitin for stuff to load.

**Comment by MattOttawa** [comment]
i also switched isWorldWonderClass() calls to isWorldWonder() on the dll.

**Comment by Toffer90** [comment]
> WonderClass

Of course, I should have figured that you had renamed those already. ^^
I'll fix that in python right now.

**Pull request merged**
