### PR TITLE
deleted CvXMLLoadUtility::RemoveTGAFiller

### PR DESCRIPTION
**Pull request by MattOttawa**
GC.getGAMEFONT_TGA_RELIGIONS() is 50 right now. This does nothing I think. MRGENIE stuff is usually complicated but pointless.

### CODE REVIEW

**Comment by Toffer90** [comment]
Its value is very important in how the tga symbol texture is read.

**Comment by MattOttawa** [comment]
Have you looked? I just searched. It's more pointless bs.

**Comment by Toffer90** [comment]
Changing the value of that global define does have a noticeable effect in-game, I changed it while I reworked the GameFont.tga files. I think its old value was 100, which was way too much and caused the game to have too few unicodes for symbols left for all the resource symbols as too many empty ones were reserved for religions and corporations.

**Comment by MattOttawa** [comment]
Hmm. I was searching the tags.

**Comment by Toffer90** [comment]
Texture modders usually never touch cpp code, so we should keep the xml define rather than hardcoding it.

**Pull request merged**
