### PR TITLE
Tech name and pedia rewrite 

### PR DESCRIPTION
**Pull request by GreatCoffers**
Rewritten many techs and pedia entires so far.

### CODE REVIEW

**Comment by KaTiON-PT** [comment]
Animal Husbandry shouldn't be called Bovoid Domestication as it doesn't just unlock bovids.

**Comment by billw2012** [comment]
Still don't understand why you have added `Tech_CIV4GameText.xml` in the root directory. All you need to do is edit and commit the *existing* `Tech_CIV4GameText.xml` in `Assets\XML\Text`.
You do NOT need to do another PR. Please just do the following:
Replace the `Assets\XML\Text\Tech_CIV4GameText.xml` with the one you added in the root directory, and remove the one you added, and commit that and push your branch. That will automatically update this Pull Request, then it will be in a state we can accept (assuming no other problems).

**Comment by raxo2222** [comment]
Notice, that you have Tech_CIV4GameText.xml in https://github.com/GreatCoffers/Caveman2Cosmos

**Comment by GreatCoffers** [comment]
> Notice, that you have Tech_CIV4GameText.xml in https://github.com/GreatCoffers/Caveman2Cosmos

Ok. I didn't notice that. I just skimed past it. My bad.

**Comment by billw2012** [comment]
Yeah looks like it's better now. However we have conflicts, and it thinks there are a lot of changes related to whitespace.
This link hides the whitespace changes (or use the cog in the diff view): https://github.com/caveman2cosmos/Caveman2Cosmos/pull/190/files?utf8=%E2%9C%93&diff=split&w=1

**Comment by GreatCoffers** [comment]
> Yeah looks like it's better now. However we have conflicts, and it thinks there are a lot of changes related to whitespace.
> This link hides the whitespace changes (or use the cog in the diff view): https://github.com/caveman2cosmos/Caveman2Cosmos/pull/190/files?utf8=%E2%9C%93&diff=split&w=1

What I'm I supposed to do now. Edit the whitespaces?

**Comment by billw2012** [comment]
> What I'm I supposed to do now. Edit the whitespaces? I was mostly spellchecking some of the pedia entries.
Nothing yet, let me have a look at it first, I was just updating you.

**Comment by GreatCoffers** [comment]
How is it going?

**Comment by KaTiON-PT** [comment]
Would be easier for you to edit CIV4TechInfos and copy/paste the changed names there from your spreadsheet.

**Comment by GreatCoffers** [comment]
> Would be easier for you to edit CIV4TechInfos and copy/paste the changed names there from your spreadsheet.

I'm not sure if we are going rename the CIV4TechInfos IDs into the real names used in the Text files. I'm going to do the opposite. I created better names for some of the techs.

**Comment by KaTiON-PT** [comment]
> > Would be easier for you to edit CIV4TechInfos and copy/paste the changed names there from your spreadsheet.
> 
> I'm not sure if we are going rename the CIV4TechInfos IDs into the real names used in the Text files. I'm going to do the opposite. I created better names for some of the techs.

No, I am asking you to grab a fresh CIV4TechInfos.xml file and edit their localisations to the better names you want to implement as that shouldn't take more than 20 minutes of copy/pasting. This way you avoid dealing with whitespaces.

**Comment by billw2012** [comment]
This is merged into master, white space is automatically fixed now. 
@GreatCoffers make sure to merge from our fork to yours to get our latest changes as well.

**Comment by KaTiON-PT** [comment]
You are great Bill, thank you.

**Comment by KaTiON-PT** [comment]
@GreatCoffers Pastoralism and Genome Browsers are mispelled. I'll warn you if I find more.

**Comment by GreatCoffers** [comment]
My spelling is not exactly the best.

**Comment by Thunderbrd** [comment]
Changes of the TXT_KEYs are usually best to keep in harmony with the <TYPE> reference.  And the <TYPE> references shouldn't be changed unless we are in a compatibility break mode in the project.  We may be in one soon and we should be noting the objects that it would be helpful to rename <TYPE> references on in the 'for next compatibility break' document.  (I'm hoping none of this is obsolete information at this point but correct me if it is.)

**Comment by raxo2222** [comment]
Thunderbrd, over 100 techs had different type and ingame names.
This is case with HUNDREDS of other stuff.

**Comment by Thunderbrd** [comment]
I'm aware of how extensive the problem is.  Techs are not the only objects that have a lot of disconnects like that.  Also units, promotions, etc...  I'm not sure why we need a tool to do this, it's just a meditative task to go through the files and correct them once we break compatibility.  It should not be done automated, imo, because we have numerous game objects with the same name as another and there are thus a number of special cases that cannot directly adhere to the texted name all the way through to the <TYPE> name - some will have to be abbreviated in a way that at least makes sense.  Automation cannot make these kinds of determinations.

**Comment by raxo2222** [comment]
I mean it could just detect all cases.

**Comment by Thunderbrd** [comment]
> Animal Husbandry shouldn't be called Bovoid Domestication as it doesn't just unlock bovids. Beyond that they all look good.

Jeez... it would at LEAST be called Bovine!  But yeah, I totally agree that Animal Husbandry should stay exactly as it is named.

**Comment by Thunderbrd** [comment]
Yeah I suppose something that could do that might help but how do you compare the wording: Axeman to UNIT_AXEMAN?  I mean, you could automatically find the disconnects between TXT_KEY and TYPE I suppose.

**Comment by Thunderbrd** [comment]
I suppose if it's possible, Bill's the guy to say how it can be done ;)

**Comment by billw2012** [comment]
I would suggest someone just do it manually with search and replace. 100 x 20 seconds to do each one = <1 hour to do it.

**Comment by raxo2222** [comment]
Well its closer to 1000 bill ;)

**Pull request merged**
