### PR TITLE
Moving #includes out of CvGameCoreDll.h

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by alberts2** [comment]
This should be done the other way around by removing all Cv* and Cy* headers from the precompiled headers. This would really speed up the compilation after making changes.

**Comment by MattOttawa** [comment]
1>1> Obj: **Isolated** C:\Users\uhm\Documents\GitHub\Caveman2Cosmos\Build\Debug\CvGameTextMgr.obj

This is from my vs output. It seems to skip CvGameTextMgr. Any idea what's it about?

**Comment by raxo2222** [comment]
It doesn't skip anything, just does this file separately from what I heard.

**Comment by Toffer90** [comment]
> 1>1> Obj: **Isolated** C:\Users\uhm\Documents\GitHub\Caveman2Cosmos\Build\Debug\CvGameTextMgr.obj
> 
> This is from my vs output. It seems to skip CvGameTextMgr. Any idea what's it about?

Bill said: `Just means that it builds outside of the unity file, i.e. builds the cpp on its own`
When I last inquired about it.

**Comment by MattOttawa** [comment]
I'm actually not sure how I want to do this. Can I add #include "CvGameCoreDLL.h" to most headers and put an include for most files that are not in the pch in one file and share the one file similar to the way CvGameCoreDLL is done? How important is it to keep #includes to a minimum?

**Comment by alberts2** [comment]
You can find some good advice at https://www.acodersjourney.com/top-10-c-header-file-mistakes-and-how-to-fix-them/

**Comment by MattOttawa** [comment]
"If you can guarantee that your code will always be compiled with compiler which understand #pragma once,you use it, otherwise you use include guards."
The guidance is for public header files/ APIs that are distributed to external parties - we don't know if their compiler supports #pragma once or not - so the include guard is necessary.
If you know your partner's compiler supports #pragma once, putting an header guard is not advisable like you mentioned.



You're right Oleksandr - putting in a check like that when the compiler supports #pragma once is a waste.

**Pull request closed without merging**
