### PR TITLE
Parallel maps move units mission

### PR DESCRIPTION
**Pull request by MattOttawa**
Am I supposed to make a mission for this or a command? Actually does anyone wanna do some of this with me? Like the xml and make empty missions on the dll?

### CODE REVIEW

**Comment by Thunderbrd** [comment]
I'd always planned to - is this where you're at with things already?  Do we have a map generation mechanism for defining the plots on another map yet?  A way to trigger the map generating?  UI to switch which map you're working with/looking at?  Save/load? 
 I'm asking because I don't really know the limits to where Koshling got us or where you have us up to.  I can see why it'd be helpful to get this part of things done soon.  Unfortunately I'm unable to offer much assistance at the moment on this but there will soon come a time when I can.

**Comment by MattOttawa** [comment]
last time you tried the python was turned off. This branch works.

The is code to trigger the map generation is in CvMap::afterSwitch(). It uses the MapType Xml. I have only tried the mapscripts.
In CvMapExternal there is a loop for the save/load of maps. Never tested.
No UI. Keys only (Alt 1).

**Comment by Thunderbrd** [comment]
> last time you tried the python was turned off. This branch works.
> 
> The is code to trigger the map generation is in CvMap::afterSwitch(). It uses the MapType Xml. I have only tried the mapscripts.
> In CvMapExternal there is a loop for the save/load of maps. Never tested.
> No UI. Keys only (Alt 1).

You're making serious headway then.  Well done!!!  We should try to get Raxo and Toffer working on the new map type mapscripts.  And some button based <> UI to switch maps.

I might find some time to help with the map switching soon since that WILL be very soon on the radar.

One thing I've been wondering: posing this question to Toffer I think - would it be possible to bring up a limited map window as part of a mission process so as to give us the ability to target plots on a different map under certain conditions in the mission?

**Comment by Toffer90** [comment]
> > last time you tried the python was turned off. This branch works.
> > The is code to trigger the map generation is in CvMap::afterSwitch(). It uses the MapType Xml. I have only tried the mapscripts.
> > In CvMapExternal there is a loop for the save/load of maps. Never tested.
> > No UI. Keys only (Alt 1).
> 
> You're making serious headway then. Well done!!! We should try to get Raxo and Toffer working on the new map type mapscripts. And some button based <> UI to switch maps.
> 
> I might find some time to help with the map switching soon since that WILL be very soon on the radar.
> 
> One thing I've been wondering: posing this question to Toffer I think - would it be possible to bring up a limited map window as part of a mission process so as to give us the ability to target plots on a different map under certain conditions in the mission?

If we could quickly read out some basic map data from the currently unloaded map, then we could add in a screen containing a 2D map with simplified graphics for plot terrain and perhaps a symbol overlay for cities and other key features of the other map. Then the player could simply click the plot and push a confirm button to indicate what plot it want the map traveler to arrive at.
I'm thinking we may have to add a new texture xml tag to terrain info that contain this simplified texture, small 64x64 button like terrain textures displayed side by side at perhaps 32x32 resolution inside a scroll window to accomodate different map sizes, having a zppm feature might be possible but perhaps to complex and cluncky to make a smooth with our current UI tools..

**Comment by raxo2222** [comment]
As for map generation, I recommend 11 zones.
https://forums.civfanatics.com/threads/guide-to-space-map-making.656681/
I listed 12 zones, but last one (hyperspace) is not needed - it can be created while playing in last era..

**Comment by Thunderbrd** [comment]
> > One thing I've been wondering: posing this question to Toffer I think - would it be possible to bring up a limited map window as part of a mission process so as to give us the ability to target plots on a different map under certain conditions in the mission?
> 
> If we could quickly read out some basic map data from the currently unloaded map, then we could add in a screen containing a 2D map with simplified graphics for plot terrain and perhaps a symbol overlay for cities and other key features of the other map. Then the player could simply select a plot and push a confirm button to indicate what plot it want the map traveler to arrive at.
> I'm thinking we may have to add a new texture xml tag to terrain info that contain the path for this simplified texture, small 64x64 button like terrain textures displayed side by side at perhaps 32x32 resolution inside a scroll window to accomodate different map sizes, having a zppm feature might be possible but perhaps to complex and cluncky to make a smooth with our current UI tools..

Outstanding thinking here.  I think you're right it's too much to ask to do a full view on the second map but some kind of in-between shorthand approach between what you have on the military advisor/minimap and the main would probably be absolutely perfect.  The map data readout I don't think should be hard but I'd think Matt might be able to provide that easier than I could.  I suppose we would need to predetermine a size for such a map... 9x9 perhaps?  That would allow for a center tile with 4 tile width shown on all sides.

We'd need to know what units are on tiles in this sort of thing so that if you were targetting a weapon or moving into the selected tile on that map, you'd know what you were doing there with an attack or if you were going to BE attacked by moving there.  It wouldn't necessarily need to be expressed in anything more than a flag or hover but that's a whole 'nother level of complex to consider.  This would also be a way to target recon missions so we'd need some obvious hard limit definition to the map edge and the ability to, if it's this sort of thing, target a tile that's 'unrevealed'.



> > You're making serious headway then. Well done!!! We should try to get Raxo and Toffer working on the new map type mapscripts. And some button based <> UI to switch maps.
> 
> As for map generation, I recommend 11 zones.
> https://forums.civfanatics.com/threads/guide-to-space-map-making.656681/
> I listed 12 zones, but last one (hyperspace) is not needed - it can be created while playing in last era..

We need to think of this in a 'beyond space only' concept as well.  Strategically, the plan includes at least one map that's tied to the definitions of the initial map, the subterranean one.  This might be the first you'd see if we enable some caves to lead into it - potentially a second map you might see in prehistoric.  But I might think to wait a bit on developing that one.

It would be good for us to consider one script at a time.  Perhaps the first should be a cislunar map.  Orbital space with an earth tile and a moon tile and an edge a bit beyond that for transitioning to the solar space map.  This probably wouldn't be terribly complicated from a scripting perspective.  Wouldn't think there'd be a high variety of terrains, although Van Allen belts might be interesting.  But I think we might need new 'features' for these celestial bodies to be placed on tiles.

**Comment by MattOttawa** [comment]
You can call GC.getMapByIndex(MapType) to get a pointer to a certain map. Then you can call plotByIndex on that map to get the correct plots.
For units, cities, selection groups, and plot groups I moved the container they're into a vector. (Copied from the first version). I'll add methods so these things can be referred to by map.

**Comment by Thunderbrd** [comment]
> You can call GC.getMapByIndex(MapType) to get a pointer to a certain map. Then you can call plotByIndex on that map to get the correct plots.
> For units, cities, selection groups, and plot groups I moved the container they're in into a vector. (Copied from the first version). I'll add methods so these things can be referred to by map.

You guys are more awesome than words can express!  This is so cool!

So Toffer, can we start building a list of the information we're going to need for this targetting screen map - and any other elements we'll need?

**Comment by MattOttawa** [comment]
Actually you can get the units and cities from the plots.

**Comment by Thunderbrd** [comment]
Ah.. yeah, just about anything about a plot if you're able to report the plot info itself sure.

**Comment by Thunderbrd** [comment]
We should be able to get improvement, bonus and feature information from that as well right?  And if it's a peak or hill.

**Comment by Toffer90** [comment]
> would need to predetermine a size for such a map... 9x9 perhaps? That would allow for a center tile with 4 tile width shown on all sides.

I was thinking the entire map with scroll bars both vertically and horizontally, so when you are asked where you want to land on the other planet you will first see the top left corner of said planet with simplified tile based graphic and then you may scroll around to the correct spot, how much of the map you see at the same time will depend on what monitor resolution you are using.

> We'd need to know what units are on tiles in this sort of thing so that if you were targetting a weapon or moving into the selected tile on that map, you'd know what you were doing there with an attack or if you were going to BE attacked by moving there. It wouldn't necessarily need to be expressed in anything more than a flag or hover but that's a whole 'nother level of complex to consider. This would also be a way to target recon missions so we'd need some obvious hard limit definition to the map edge and the ability to, if it's this sort of thing, target a tile that's 'unrevealed'.

We could add the unit icon of the best defender as a small overlay on the map, and add in tooltip information about all units there when mousing over the top defender unit icon.

> It would be good for us to consider one script at a time. Perhaps the first should be a cislunar map. Orbital space with an earth tile and a moon tile and an edge a bit beyond that for transitioning to the solar space map. This probably wouldn't be terribly complicated from a scripting perspective. Wouldn't think there'd be a high variety of terrains, although Van Allen belts might be interesting. But I think we might need new 'features' for these celestial bodies to be placed on tiles.

Best to start with a simple mapscript we already have, like fractal or arboria. When we are confident the technical part of switching between x amount of maps work then we can put some effort into developing new mapscripts for space content.

**Comment by Thunderbrd** [comment]
> I was thinking the entire map with scroll bars both vertically and horizontally, so when you are asked where you want to land on the other planet you will first see the top left corner of said planet with simplified tile based graphic and then you may scroll around to the correct spot, how much of the map you see at the same time will depend on what monitor resolution you are using.

That sounds even better!



> We could add the unit icon of the best defender as a small overlay on the map, and add in tooltip information about all units there when mousing over the top defender unit icon.

Perfect.  Yes.




> Best to start with a simple mapscript we already have, like fractal or arboria. When we are confident the technical part of switching between x amount of maps work then we can put some effort into developing new mapscripts for space content.

If I'm not mistaken, we're already successfully there, are we not Matt?  You were using something here...

> I have only tried the mapscripts.
> In CvMapExternal there is a loop for the save/load of maps. Never tested.

Perhaps we need to consider how we pass parameters to define the map script to be used for generation somehow.  I like that Koshling included the ability to use a preset map in a given map creation call as well and how we can let players set that up is... I guess another front on this project entirely.  Maybe when a new map is to be made, we need to send up a popup for the player to define the script for it (perhaps with a type filter and we need to give scripts a define for type) or define the preset map for it.  And 'which player' if it's in a multiplayer game is as interesting a question... I guess player 0 but sometimes the human ends up not being player 0 on some options.  hmm...

**Comment by MattOttawa** [comment]
Max number of maps is limited by the number of MapTypes in the xml and the initial map counts as the first.
Combining CvMapInfo and CvMapCategoryInfo and deleting CvMapSwitchInfo is something I'd like to do.

**Comment by raxo2222** [comment]
Map category info is defining map categories, then they are used to group terrains.
Terrains can belong to multiple map categories.

**Comment by Toffer90** [comment]
> Map category info is defining map categories, then they are used to group terrains.
> Terrains can belong to multiple map categories.

I don't think we need plots to have map categories when we actually have multi-maps.
Terrain/feature type of plot and the map type (not tied to CvPlot, only part of CvMap) should be sufficient data to build game rules around.

**Comment by raxo2222** [comment]
> 
> 
> > Map category info is defining map categories, then they are used to group terrains.
> > Terrains can belong to multiple map categories.
> 
> I don't think we need plots to have map categories when we actually have multi-maps.
> Terrain/feature type of plot and the map type (not tied to CvPlot, only part of CvMap) should be sufficient data to build game rules around.

Well Cislunar and Lunar map category will exist in one map zone.
Solar System and Venusian/Martian/Titan.
Same with Transtellar and Plasma.

Unless you want to splice up into 20 zones, for example cislunar/solar system/near stars space would be empty and you could go to surface of moon/various objects/stars.
Also some buildings require terrain of another map category.

**Comment by Toffer90** [comment]
I'm not entirely sure what we'll end up with, maybe we want some **space maps** where planets are represented as plot features, and then some planet maps where there is no space as the planet should be possible to circumnavigate (move west infinity without ever leaving the planet).

We need to consider what kind of archetype map types we want.
I imagined these two archetypes:
 • Space map without any land terrains (Don't think we typically want these to wrap).
 • Planet maps without any space (x-wrap would be typical) Could perhaps have some orbit space at top and bottom where the poles would have been.

**Comment by raxo2222** [comment]
How transtellar space map will be represented then? There would be 10 - 30 individual stars. Also there are 7 different planet features meant to be near stars, and rogue planet/white dwarf features that can but doesn't have to be in middle of nowhere.
This allows two different types of cities: ones in transtellar space and one on star terrain.
This mirrors Cislunar/Lunar cities and Solar System/Mars, Venus, Titan city.
Other solar system terrains have Jovian mapcategory which pretty much is "this is planet/moon/asteroid terrain"

**Comment by Toffer90** [comment]
I haven't though much on the details, nice thing about representing whole planets or stars inside one plot as a feature is that they can be a 3D sphere at different scales that rotates at a set speed, would look better on the map than flat terrain in the middle of space.

**Comment by raxo2222** [comment]
So those would be displayed like in final frontier then.

**Comment by Toffer90** [comment]
The style and scale we go for for non-classical maps is a matter for discussion for sure.

**Comment by Thunderbrd** [comment]
> > Map category info is defining map categories, then they are used to group terrains.
> > Terrains can belong to multiple map categories.
> 
> I don't think we need plots to have map categories when we actually have multi-maps.
> Terrain/feature type of plot and the map type (not tied to CvPlot, only part of CvMap) should be sufficient data to build game rules around.

We still will - it will stand as a sort of 'domain' type in that way, helping to define where some units cannot go, spawn, etc... and we're going to need to define city types and the map types they can go on for things like barb city spawns and special city locations and guiding their graphics.  It was also always meant to help be a natural limiter for what kind of terrains can even be placed on a particular type of map.

**Comment by Thunderbrd** [comment]
> > > Map category info is defining map categories, then they are used to group terrains.
> > > Terrains can belong to multiple map categories.
> > 
> > 
> > I don't think we need plots to have map categories when we actually have multi-maps.
> > Terrain/feature type of plot and the map type (not tied to CvPlot, only part of CvMap) should be sufficient data to build game rules around.
> 
> Well Cislunar and Lunar map category will exist in one map zone. (Cislunar space and Moon)
> Solar System and Venusian/Martian/Titan (Solar System and Venus, Mars, Titan).
> Same with Transtellar and Plasma (Transtellar space and brown/red/yellow star terrains).
> 
> Unless you want to splice up into 20 zones, for example cislunar/solar system/near stars space would be empty and you could go to surface of moon/various objects/stars.
> Also some buildings require terrain of another map category.

The intent from the beginning was to have a cislunar map with an earth orb feature and a moon orb feature.  The lunar map would be its own map entirely that you could transition to from the cislunar map to and vice versa.  Then going beyond the cislunar map, you'll go into the solar system map, where you'd see the planets as orbs and so on.  Going beyond that map you'd enter the galactic map where the star systems are shown on plots, though I think there was something about an Orion's arm map before it becomes truly galactic.

**Pull request closed without merging**
