### PR TITLE
Cleanups and updates

### PR DESCRIPTION
**Pull request by SannitaSSJ**
**Sorting alphabetically + updating**
* CIV4ArtDefines_Civilization
* CIV4BasicInfos
* CIV4CivicOptionsInfos
* CIV4MemoryInfos
* CIV4NewConceptInfos
* Culture_CIV4ArtDefines_Bonus
* PopUp_CIV4GameText
* TradeGoods_CIV4ArtDefines_Bonus
* TradeGoods_CIV4BonusInfos
* Unit_Naming
* zDepend_Entertainer_Animals_CIV4UnitInfos

**Deleting files (and integrating texts into respective files)**
* Brackenspore_CIV4GameText
* Concrete_CIV4GameText
* LeadGlass_CIV4GameText
* Mammoth_Help_CIV4GameText

**Fixing names and tags**
* Afghanistan --> Afghan
* Galapogos --> Galapagos
* Hattian --> Haitian
* Philistines --> Philistine
* Terra Sigilliata --> Terra Sigillata
* Xiongu --> Xiongnu

...and truly a lot of minor fixes and cleanups

### CODE REVIEW

**Comment by raxo2222** [comment]
@SannitaSSJ you can't rename tags anymore - we left savebreaking period.

**Comment by SannitaSSJ** [comment]
> @SannitaSSJ you can't rename tags anymore - we left savebreaking period.

You mean ever, or for the time being?

(I'll just change this to draft, BTW)

**Comment by raxo2222** [comment]
This may be one year at minimum or so.
You can change TXT keys and texts though

**Comment by raxo2222** [comment]
You changed LOT of art file patches!

Did you move files accordingly in unloaded art folder?

**Comment by SannitaSSJ** [comment]
> You changed LOT of art file patches!
> Did you move files accordingly in unloaded art folder?

Uhhhh, I think I did my best, but I'm not sure about this.

**Comment by raxo2222** [comment]
You also broke other things too
assert:
info type 'CIVICOPTION_AGICULTURE' not found, Current XML file is: xml\GameInfo\CIV4CivicInfos.xml

As if you failed to rename thing everywhere.

**Comment by SannitaSSJ** [comment]
> You also broke other things too
[...]
> As if you failed to rename thing everywhere.

I don't know why, I always make full search on all files on my local folder, and I update it also twice a day...

**Comment by raxo2222** [comment]
I guess you didn't search in *.xml but in more specific files.

**Comment by raxo2222** [comment]
Looks like it would just reset some renamed units/buildings/bonuses, this would be disruptive but not save breaking,

**Comment by Toffer90** [comment]
> Looks like it would just reset some renamed units/buildings/bonuses, this would be disruptive but not save breaking,

Renaming bonus type names shouldn't even be disruptive I think.

**Pull request merged**
