### PR TITLE
Changed tech names to be better representative of what they are

### PR DESCRIPTION
**Pull request by GreatCoffers**

### CODE REVIEW

**Comment by raxo2222** [comment]
25000 changed lines.... what did you here?
Probably you messed up formatting somewhere

**Comment by GreatCoffers** [comment]
> 25000 changed lines.... what did you here?
> Probably you messed up formatting somewhere

I'm not sure. It's not changed that often. I modified it from an earlier version of C2C pre-Prehistoric revamp.

**Comment by billw2012** [comment]
Yeah this is better thanks @GreatCoffers! Although yeah you seem to have converted white space or line endings in this file. Please make sure to leave tabs as tabs! Line endings should already be correctly set by our .gitattributes file.

**Comment by raxo2222** [comment]
> 
> 
> > 25000 changed lines.... what did you here?
> > Probably you messed up formatting somewhere
> 
> I'm not sure. It's not changed that often. I modified it from an earlier version of C2C pre-Prehistoric revamp.

First update it, then add your changes. Also don't convert any tabs/white spaces

**Comment by KaTiON-PT** [comment]
I feel you should @ pepper2000 on the forums as you are changing a lot of techs he introduced, and he might not like that.

**Comment by GreatCoffers** [comment]
> > > 25000 changed lines.... what did you here?
> > > Probably you messed up formatting somewhere
> > 
> > 
> > I'm not sure. It's not changed that often. I modified it from an earlier version of C2C pre-Prehistoric revamp.
> 
> First update it, then add your changes. Also, don't convert any tabs/white spaces
> 
> File was updated on prehistoric revamp

I'm modifying the pedia text as well, so that may be causing most of the deletions/problems.

**Comment by billw2012** [comment]
> I'm modifying the pedia text as well, so that may be causing most of the deletions/problems.
No, its whitespace changes. If you disable whitespace in the diff you can see the problems go away.
As raxo said you should always make changes on the latest version of the file, NEVER copy an old version of the file into a new version or you write over all the changes done to it.
And make sure whatever editor you use is not set to convert tabs to spaces, or change line endings.

**Comment by billw2012** [comment]
For future reference: It wasn't necessary to close this PR, if you commit new fixes to your branch they will automatically be applied to the Pull Request that is active.

**Pull request closed without merging**
