### PR TITLE
modified IDValueMap so value can be an array

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by MattOttawa** [comment]
I need xml and schema for new tag to see if this works. You do that raxxo?

**Comment by raxo2222** [comment]
Yeah

**Comment by raxo2222** [comment]
Those are fractional tech commerce changes - that is +x or -x to value
Not +-% modifiers

**Comment by raxo2222** [comment]
I think it would be easier if you first converted bonus commerce percents to idvalue map, and then wrote tech commerce percents in idvalue form

**Pull request merged**
