### PR TITLE
Bonus XML file - fix all labels + some descriptions

### PR DESCRIPTION
**Pull request by SannitaSSJ**
fix alphabetical order (again) + update of all labels + full update descriptions (A-G, X-Y) + general cleanup of descriptions (H-W, Z)

### CODE REVIEW

**Comment by Toffer90** [comment]
Is this one ready for merge?

**Comment by raxo2222** [comment]
I need to check if he didn't cause TXT key issues and bonuses needs to be renamed if he changed their names

**Comment by raxo2222** [comment]
I need to check if he didn't cause TXT key issues and bonuses needs to be renamed if he changed their names

**Comment by SannitaSSJ** [comment]
> Is this one ready for merge?

Labels are done, while descriptions aren't. (TBH, I wanted only to push labels without new descriptions, but I didn't know any new commit would be included in this merge)

IMHO, it's already enough work to be included in the mod. I cannot give you an end date for completing descriptions 'coz I'll be extremely busy up to the first week of March. Your call, there's no prob if we decide to wait until all descriptions are done.

**Comment by SannitaSSJ** [comment]
> IMHO, it's already enough work to be included in the mod. [...] Your call, there's no prob if we decide to wait until all descriptions are done.

A minor update: I completed a basic cleanup of all descriptions, i.e. removed all double spaces, references to external sites (Wikipedia, other http addresses) or to other mods, etc. IMHO it's sufficiently good to go, but as I said yesterday it's your call now to include it already or wait until I'll finish (which, in the good case scenario, will be by the end of March/beginning of April).

**Pull request merged**
