### PR TITLE
Forest planting and aging

### PR DESCRIPTION
**Pull request by Toffer90**
Added woodland life cycle python script from MToS
Tweaked the worker builds dealing with planting forests.

Please help me test this in-game as I have little time for it.
Watch the worker build actions "Grow forest" and "Plant Forest" in particular.
I suspect some discussion, changes, and polish is needed before a merge.

### CODE REVIEW

**Comment by Toffer90** [comment]
Odd that appveyor failed to build it, I built an assert and a release build locally just fine, and the missing xml tag it complains about is clearly setup as optional in the dll just like another tag that is missing from almost every other featureStruct clauses in the build XML.

**Comment by raxo2222** [comment]
> 
> 
> Odd that appveyor failed to build it, I built an assert and a release build locally just fine, and the missing xml tag it complains about is clearly setup as optional in the dll just like another tag that is missing from almost every other featureStruct clauses in the build XML.

It failed because there was some typo in it.
Validating C:\projects\caveman2cosmos\Assets\Xml\Units\CIV4BuildInfos.xml
5229,7: The element 'FeatureStruct' in namespace 'x-schema:../Schema/C2C_CIV4UnitSchema.xml' has incomplete content. List of possible elements expected: 'x-schema:../Schema/C2C_CIV4UnitSchema.xml:bRemove'.

**Comment by MattOttawa** [comment]
Looks good.

**Comment by Toffer90** [comment]
Has this branch been play tested a bit by anyone?
I think it's safe enough to merge before the next release, but not without any testing.
I haven't had time for testing this myself, though I know the woodland life-cycle implemented in python works well as I've had in in the MToS modmod for a long time now. It's the worker plant forest builds that needs testing.

**Comment by Thunderbrd** [comment]
I haven't and probably won't have time budgeted to either for a while.

**Comment by Toffer90** [comment]
> I haven't and probably won't have time budgeted to either for a while.

No worry, I'm just curious if someone have already tested these changes without expressing that they did.

**Comment by MattOttawa** [comment]
I just start up game and play couple turns. Not the testing your looking for I think.

**Comment by Toffer90** [comment]
> I just start up game and play couple turns. Not the testing your looking for I think.

That's the same amount of testing as I did when making the branch.  ^^

**Pull request merged**
