### PR TITLE
Text key validator

### PR DESCRIPTION
**Pull request by MattOttawa**
Attempt number 3

Referenced key not found: Beyond the Sword

Referenced key not found: BTS Classical

Referenced key not found: Civilization IV

Referenced key not found: Warlords

Referenced key not found: TXT_KEY_SPECIALIST_CITIZEN_STRATEGY

Referenced key not found: TXT_KEY_SPECIALIST_SETTLED_SLAVE_STRATEGY

Referenced key not found: ATTACHABLE_SMOKE

Referenced key not found: Looks like little white things flying behind plane

Referenced key not found: Dark Oil Smoke for the 4th Damage State of the Tanks

Referenced key not found: Dark Oil Smoke for the 4th Damage State of Artillery

Referenced key not found: Dark Oil Smoke for the 4th Damage State of MachineGunner

Referenced key not found: Dark Oil Smoke for the 4th Damage State of the Gunship

Referenced key not found: DarkSmoke for the 4th Damage State of the Catapult

Referenced key not found: DarkSmoke for the 4th Damage State of the Caravel

Referenced key not found: DarkSmoke for the 4th Damage State of the Frigate

Referenced key not found: DarkSmoke for the 4th Damage State of the Ironclad

Referenced key not found: DarkSmoke for the 4th Damage State of the Galleon

Referenced key not found: DarkSmoke for the 4th Damage State of the Galley

Referenced key not found: DarkSmoke for the 4th Damage State of the Transport

Referenced key not found: DarkSmoke for the 4th Damage State of the Destroyer

Referenced key not found: DarkSmoke for the 4th Damage State of the Battleship

Referenced key not found: DarkSmoke for the 3rd Damage State of the Carrier

Referenced key not found: DarkSmoke for the 4th Damage State of the Carrier

Referenced key not found: DarkSmoke for the 4th Damage State of the Plane

Referenced key not found: DarkSmoke for the 4th Damage State of the JetFighter

Referenced key not found: DarkSmoke for the 4th Damage State of the Bomber

Referenced key not found: DarkSmoke for the 4th Damage State of the Stealth Bomber

Referenced key not found: DarkSmoke for the Smoke Stack of the Ironclad

Referenced key not found: JetFighter Bomb Contrail

Referenced key not found: JetFighter Missile Contrail

Referenced key not found: JetFighterAfterburn

Referenced key not found: ICBM Afterburn

Referenced key not found: SubmarineTorpedo Bubbles

Referenced key not found: SubmarineBubbles

Referenced key not found: Side Froth for the Submarine

Referenced key not found: DarkSmoke for the 4th Damage State of the Submarine

Referenced key not found: Bow Froth for the Battleship

Referenced key not found: Side Froth for the Battleship

Referenced key not found: Bow Froth for the Carrier

Referenced key not found: Side Froth for the Carrier

Referenced key not found: Bow Froth for the Caravel

Referenced key not found: Side Froth for the Caravel

Referenced key not found: Bow Froth for the Destroyer

Referenced key not found: Side Froth for the Destroyer

Referenced key not found: Bow Froth for the Frigate

Referenced key not found: Side Froth for the Frigate

Referenced key not found: Bow Froth for the Galleon

Referenced key not found: Side Froth for the Galleon

Referenced key not found: Bow Froth for the Galley

Referenced key not found: Side Froth for the Galley

Referenced key not found: Bow Froth for the Ironclad

Referenced key not found: Side Froth for the Ironclad

Referenced key not found: Bow Froth for the Transport

Referenced key not found: Side Froth for the Transport

Referenced key not found: Bow Froth for the Workboat

Referenced key not found: Side Froth for the Workboat

Referenced key not found: Highlight effect for the Prophet

Referenced key not found: Highlight effect for the Scientist

Referenced key not found: Highlight effect for the Merchant

Referenced key not found: Highlight effect for the Great Artist

Referenced key not found: Highlight effect for the Engineer

Referenced key not found: Highlight effect for the Warlord

Referenced key not found: BlackSmoke on Omen 4 Horsemen

Referenced key not found: GreenSmoke on Famine Horseman

Referenced key not found: Goody hut pop dust and hay

Referenced key not found: Improvements campfire

Referenced key not found: Improvements chimney smoke

Referenced key not found: Fire for improvement fire place

Referenced key not found: Steam for improvements

Referenced key not found: ICBM greenglow

Referenced key not found: Invasion Ship Engine Glow

Referenced key not found: Invasion Ship Engine Thrust

Referenced key not found: Invasion Ship Forcefield

Referenced key not found: EFFECT_FOOTSTEP_ON

Referenced key not found: Footstep

Referenced key not found: Ping

Referenced key not found: Res Bomb

Referenced key not found: Stasis

Referenced key not found: Waypoint

Referenced key not found: Laser Hit

Referenced key not found: Mine

Referenced key not found: Mutiny

Referenced key not found: Candle flame for religion popup cinematic

Referenced key not found: Candle flame hardware light for religion popup cinematic

Referenced key not found: Footprint

Referenced key not found: Footprint Medium

Referenced key not found: Footprint Small

Referenced key not found: Horse Hoof Print

Referenced key not found: Wild Animal Paw Print

Referenced key not found: Assault Mech Print

Referenced key not found: ArrowProjectile3D

Referenced key not found: Longbow Arrow

Referenced key not found: Crossbow bolt

Referenced key not found: ArcherArrow

Referenced key not found: ChineseArcherArrow

Referenced key not found: EgyptianArcherArrow

Referenced key not found: EurasianArcherArrow

Referenced key not found: Galley Fire Arrow Effect

Referenced key not found: CamelArcherArrow

Referenced key not found: HorseArcherArrow

Referenced key not found: Mali Spear

Referenced key not found: Catapult Rock

Referenced key not found: Grenadier Grenade

Referenced key not found: Hwacha Rocket fire

Referenced key not found: Sam_Infantry missle

Referenced key not found: Peltast Sling Stone

Referenced key not found: Mongolian Javelin

Referenced key not found: Trebuchet Rock

Referenced key not found: Dust Cloud

Referenced key not found: Goody hut pop dust and hay Used for Yert to Mongol Settler

Referenced key not found: Hot Sparks

Referenced key not found: Quick Puff of Dirt

Referenced key not found: Quick Clump of Dirt

Referenced key not found: Creation Effect

Referenced key not found: Spy Sabotaging Production

Referenced key not found: Omen Horsemen attack

Referenced key not found: Dust as the Siege tower dies

Referenced key not found: B-52's bomb explosion

Referenced key not found: Jet Fighter Missile

Referenced key not found: Jet Fighter Bomb Animations

Referenced key not found: Jet Fighter Nuke Animations

Referenced key not found: Bomber Bomb Animations

Referenced key not found: Stealth Bomber Bomb Animations

Referenced key not found: Nuke Bomb Explosion

Referenced key not found: Jet Fighter Bomb Explosion

Referenced key not found: Stealth BomberBomb Explosion

Referenced key not found: Bomber Bomb Explosion

Referenced key not found: Stealth Bomber's bomb explosion

Referenced key not found: Jet Fighter's missile explosion

Referenced key not found: The Nuclear Explosion

Referenced key not found: Small fire ball for on ICBM

Referenced key not found: Large fire ball for on ICBM

Referenced key not found: Laser Effect for a Blocked ICBM

Referenced key not found: Boulder explosion in Dirt

Referenced key not found: Small Rock explosion for a Hit Catapult

Referenced key not found: Boulder explosion for Catapult Death

Referenced key not found: Artillery's Shell explosion

Referenced key not found: Death fire for wooden cannon

Referenced key not found: large fire ball for on airplanes

Referenced key not found: Small fire ball for on airplanes

Referenced key not found: Small fire ball for on Fighter

Referenced key not found: large fire ball for on Fighter

Referenced key not found: Small fire ball for on Bomber

Referenced key not found: large fire ball for on Bomber

Referenced key not found: Small fire ball for on Jet Fighter

Referenced key not found: large fire ball for on Jet Fighter

Referenced key not found: Small fire ball for on Stealth Bomber

Referenced key not found: large fire ball for on Stealth Bomber

Referenced key not found: Variation 01 for Gunship

Referenced key not found: Variation 02 for Gunship

Referenced key not found: Large Explosion for the death of the Gunship

Referenced key not found: Grenadier grenade explosion

Referenced key not found: Small oily hit explosion

Referenced key not found: Larger Oily hit explosion for Transport Version 1

Referenced key not found: Smaller Oily hit explosion for Transport Version 2

Referenced key not found: Larger Oily hit explosion for Destroyer

Referenced key not found: Smaller Oily hit explosion for Destroyer

Referenced key not found: Larger Oily hit explosion for Carrier

Referenced key not found: Smaller Oily hit explosion for Carrier

Referenced key not found: Oily smoke for high damage on late vehicles

Referenced key not found: Oily smoke and fire for high damage on late vehicles

Referenced key not found: explosion when late modern mechanical units bite the dust

Referenced key not found: explosion when early modern mechanical units bite the dust

Referenced key not found: Shockwave to add to specific unit explosion

Referenced key not found: Large death explosion for gunpowder water-vehicles

Referenced key not found: Large death explosion for Caravel

Referenced key not found: Large death explosion for Galleon

Referenced key not found: Large death explosion for Frigate

Referenced key not found: Large death explosion for Ironclad

Referenced key not found: Large death explosion for WorkBoat Modern

Referenced key not found: Large death explosion for Destroyer

Referenced key not found: Large death explosion for Battleship

Referenced key not found: Large death explosion for Oil water-vehicles

Referenced key not found: Explosion in Dirt

Referenced key not found: Explosion for on hard surfaces like modern vehicles

Referenced key not found: Variation 01 for Tanks

Referenced key not found: Variation 02 for Tanks

Referenced key not found: Variation 03 for Tanks

Referenced key not found: Large Explosion for the death of a tank

Referenced key not found: Variation 01 for Artillery

Referenced key not found: Variation 02 for Artillery

Referenced key not found: Large Explosion for the death of Artillery

Referenced key not found: Variation 01 for MachineGunner

Referenced key not found: Variation 02 for MachineGunner

Referenced key not found: Large Explosion for the death of MachineGunner

Referenced key not found: Explosion for on surface of plane before fireball

Referenced key not found: explosion when small planes hit the ground

Referenced key not found: explosion when large planes hit the ground

Referenced key not found: Machine gun shot hitting vehicle or unit

Referenced key not found: Machine gun shot hitting dirt

Referenced key not found: aircraft machine gun impact explosion with dirt flying up

Referenced key not found: Cannonball impact

Referenced key not found: Small Gunpowdery hit explosion for water-vehicles

Referenced key not found: Small Gunpowdery hit explosion for Caravel Version 1

Referenced key not found: Small Gunpowdery hit explosion for Caravel Version 2

Referenced key not found: Small Gunpowdery hit explosion for Galleon Version 1

Referenced key not found: Small Gunpowdery hit explosion for Galleon Version 2

Referenced key not found: Small Gunpowdery hit explosion for Frigate Version 1

Referenced key not found: Small Gunpowdery hit explosion for Frigate Version 2

Referenced key not found: Small Gunpowdery hit explosion for Ironclad Version 1

Referenced key not found: Small Gunpowdery hit explosion for Ironclad Version 2

Referenced key not found: Small Gunpowdery hit explosion for WorkboatModernVersion 1

Referenced key not found: Small Gunpowdery hit explosion for WorkboatModernVersion 2

Referenced key not found: Small oily hit explosion for water-vehicles

Referenced key not found: pre gunpowder small flash impact on early vessels

Referenced key not found: Small splashy hit for submarine

Referenced key not found: Small splash hit for submarine

Referenced key not found: Small explosion hit for submarine

Referenced key not found: Large Death Explosion for Submarine

Referenced key not found: Explosion Over Land

Referenced key not found: One big city sized explosion

Referenced key not found: OLD Bombard

Referenced key not found: OLD Ship Explosion Over Water

Referenced key not found: Small Gunpowdery hit explosion for Cannon Version 1

Referenced key not found: Small Gunpowdery hit explosion for Cannon Version 2

Referenced key not found: Large death explosion for Cannon

Referenced key not found: Frosty swirling air flow

Referenced key not found: aircraft jet engine contrail smoke

Referenced key not found: missile contrail smoke

Referenced key not found: Jet afterburn

Referenced key not found: air flow behind bomb

Referenced key not found: Cannonball smoke trail

Referenced key not found: Catapult Boulder smoke trail

Referenced key not found: Ironclad smokestack smoke

Referenced key not found: Hoof dust for a running horse

Referenced key not found: Tank Unit Exhaust

Referenced key not found: Gunpowdery smoke for high damage on water-vehicles

Referenced key not found: Gunpowdery smoke and fire for high damage on water-vehicles

Referenced key not found: Oily smoke for high damage on water-vehicles

Referenced key not found: OIly smoke and fire for high damage on water-vehicles

Referenced key not found: Smokey discharge for highest level of unit damage

Referenced key not found: Fire with smoke for highest level of unit damage

Referenced key not found: Dark Smoke

Referenced key not found: aircraft machine gun fire

Referenced key not found: Gunship machine gun fire

Referenced key not found: Boulder Explosion for Catapult Attack

Referenced key not found: Fighter machine gun fire

Referenced key not found: Rifleblast for flintlock rifle

Referenced key not found: Old rifleblast more powerful

Referenced key not found: Rifleblast for modern rifle

Referenced key not found: MachineGun Blast for Transport

Referenced key not found: smokeblast for front of SAM launcher as it fires

Referenced key not found: Exhaust for rear of SAM launcher as it fires

Referenced key not found: ancient cannonfire

Referenced key not found: a variant of ancient cannonfire

Referenced key not found: yet another variant of ancient cannonfire

Referenced key not found: Caravel Cannon Fire Version 1

Referenced key not found: Caravel Cannon Fire Version 2

Referenced key not found: Galleon Cannon Fire Version 1

Referenced key not found: Galleon Cannon Fire Version 2

Referenced key not found: Caravel Cannon Fire Version 3

Referenced key not found: Frigate Cannon Fire Version 1

Referenced key not found: Frigate Cannon Fire Version 2

Referenced key not found: Frigate Cannon Fire Version 3

Referenced key not found: Ironclad Cannon Fire Version 1

Referenced key not found: Ironclad Cannon Fire Version 2

Referenced key not found: Ironclad Cannon Fire Version 3

Referenced key not found: Modern cannonfire for Armoured vehicles

Referenced key not found: Modern Cannonfire For Naval ships

Referenced key not found: Modern Cannonfire For Destroyer Version 1

Referenced key not found: Modern Cannonfire For Destroyer Version 2

Referenced key not found: Modern Cannonfire For Battleship Version 1

Referenced key not found: Modern Cannonfire For Battleship Version 2

Referenced key not found: Modern Weapon Fire for Carrier attacks

Referenced key not found: Torpedo for Submarine

Referenced key not found: Panzer Tank Cannon Fire 

Referenced key not found: Cannon Fire

Referenced key not found: Artillery Cannon Fire 

Referenced key not found: MachineGunner Fire

Referenced key not found: Modern Cannonfire for Howitzer type cannons

Referenced key not found: Machanized Infantry Shell Blast

Referenced key not found: Unit Healing effect

Referenced key not found: Lotus Appearing Effect in the Buddhist Animations

Referenced key not found: Promotion for unit

Referenced key not found: Enemy glow for unit

Referenced key not found: Promotion for Interface

Referenced key not found: Creation Effect Dim

Referenced key not found: Creation Effect Bright

Referenced key not found: Creation Effect Bright Fast

Referenced key not found: Activation effect for Buddhist missionary

Referenced key not found: Activation effect for Confuscian missionary

Referenced key not found: Activation effect for Christian missionary

Referenced key not found: Activation effect for Hindu missionary

Referenced key not found: Activation effect for Islamic missionary

Referenced key not found: Activation effect for Jewish missionary

Referenced key not found: Activation effect for Tao missionary

Referenced key not found: Activation effect for the King Baby!

Referenced key not found: The King is Born Baby!

Referenced key not found: Highlight effect for the King. That's right little mama!

Referenced key not found: Activation effect for Engineer

Referenced key not found: Birth effect for the engineer

Referenced key not found: Gear effect for the Engineer

Referenced key not found: Activation effect for Prophet

Referenced key not found: Birth effect for the Prophet

Referenced key not found: Activation effect for Scientist

Referenced key not found: Birth effect for the Scientist

Referenced key not found: Activation effect for Merchant

Referenced key not found: Birth effect for Merchant

Referenced key not found: Activation effect for the warlord general

Referenced key not found: Birth of the Warlord

Referenced key not found: water submerged explosion for submarine death

Referenced key not found: Ship_Bow_Froth

Referenced key not found: Ship_Side_Froth

Referenced key not found: Ship_Sinking_Froth

Referenced key not found: Galley_Sinking_Froth

Referenced key not found: Water Plume Splash Small

Referenced key not found: Caravel Sinking_Froth

Referenced key not found: Galleon Sinking_Froth

Referenced key not found: Ironclad Sinking_Froth

Referenced key not found: Transport_Sinking_Froth

Referenced key not found: Frigate Sinking_Froth

Referenced key not found: Battleship Sinking_Froth

Referenced key not found: Carrier Sinking_Froth

Referenced key not found: WorkBoat_Sinking_Froth

Referenced key not found: Workboat Water Plume Splash

Referenced key not found: Water plume splash Large

Referenced key not found: water bubbles for submarine etc

Referenced key not found: One fog emiter to create a bank of them with 

Referenced key not found: Birds flying out and fading.

Referenced key not found: RED firework large slow

Referenced key not found: GREEN firework large slow

Referenced key not found: PURPLE firework large slow

Referenced key not found: YELLOW firework large slow

Referenced key not found: BLUE firework large slow

Referenced key not found: improvements campfire

Referenced key not found: Fire blowing out of top of Mine smelter

Referenced key not found: STEAM

Referenced key not found: Chimney smoke for improvements

Referenced key not found: Fire for mountain mine torch

Referenced key not found: Torchfire made for the colossus

Referenced key not found: fake event so that spyxml doesnt freak out

Referenced key not found: Fire for AGE OF GODS Ianna shrine

Referenced key not found: Chimney smoke for cities (variation)

Referenced key not found: Smoke for destroyed cities (variation)

Referenced key not found: underlit smoke for unhappy cities (variation)

Referenced key not found: underlit smoke for occupied cities

Referenced key not found: Fire for zoomed out unhappy citees

Referenced key not found: Fumes for diseased citees

Referenced key not found: Pulsing glow for irradiated citees

Referenced key not found: Air to Ground Machine Gun

Referenced key not found: Air to Air Machine Gun

Referenced key not found: Stealh Bomber Bomb

Referenced key not found: Galley Arrows

Referenced key not found: Small explosion for Invasion Ship

Referenced key not found: Large explosion for Invasion Ship

Referenced key not found: Powerup laser effect

Referenced key not found: Standard laser effect

Referenced key not found: Smaller laser effect

Referenced key not found: Red pulse cannon

Referenced key not found: Space radio signals

Referenced key not found: Colony settling effect

Referenced key not found: Hellhound Flamethrower

Referenced key not found: C.Cyborgt Flamethrower

Referenced key not found: Rifleblast for Flamethrower

Referenced key not found: Activation effect for Kemetism missionary

Referenced key not found: Activation effect for Hellenic missionary

Referenced key not found: Activation effect for Naghual missionary

Referenced key not found: Activation effect for Zoroastrian missionary

Referenced key not found: Primitive plasma thrower effect

Referenced key not found: particle projectile cannon

Referenced key not found: Yumi Arrow

Referenced key not found: Blood splatter effect

Referenced key not found: Blood spray effect

Referenced key not found: Stone Bullet

Referenced key not found: Canoe Plain Arrow Effect

Referenced key not found: boomerang throw

Referenced key not found: Balloon Projectile

Referenced key not found: Silk of the Giant Spider

Referenced key not found: Forest fire

Referenced key not found: TXT_KEY_BONUS_PEGASUS_PEDIA

Referenced key not found: TXT_KEY_BONUS_QUETZALCOATL_PEDIA

Referenced key not found: TXT_KEY_BONUS_CRYSTAL_GLASSWARE_PEDIA

Referenced key not found: TXT_KEY_BONUS_FAKE_GEMS_PEDIA

Referenced key not found: TXT_KEY_BONUS_MING_VASE_PEDIA

Referenced key not found: TXT_KEY_UNITCOMBAT_NOMAD

### CODE REVIEW

**Comment by raxo2222** [comment]
Does this check vanilla texts too?

If not then those could be copied from vanilla.

**Comment by MattOttawa** [comment]
I don't know if everything is working right, but ya, it's supposed to search civ4 and bts folders.

**Comment by raxo2222** [comment]
Then it doesn't search base game.
TXT_KEY_CONCEPT_GREAT_GENERALS is in Warlords\Assets\XML\Text\CIV4GameText_Warlords.xml

**Comment by MattOttawa** [comment]
You want me to skip the CIV4AttachableInfos.xml file or all the the ones that don't start with TXT_KEY?

And maybe putting the vanilla ones in the mod might be good so I could add this script to the github checks. Maybe.

**Comment by raxo2222** [comment]
By the way there are
<Civilopedia>
<Strategy>
<Quote>
<Help>
tags too.

**Comment by raxo2222** [comment]
CIV4AttachableInfos.xml and CIV4MainMenus.xml should be ignored.

Also there are TXT KEY references in python and cpp files too.

**Comment by raxo2222** [comment]
Assets/Python/Tools/TextKeyValidator.py

Those shouldn't be in mod files!
They are modding tools not part of game.

They could be in Tools/ModValidating or something like that - so there would be different tools to check if things in mod are linked properly like text, art and sounds.

**Comment by SannitaSSJ** [comment]
FYI, Bonus missing TXT's were already taken care of with #952

**Pull request closed without merging**
