### PR TITLE
Merge of animals XML GameText

### PR DESCRIPTION
**Pull request by SannitaSSJ**
This branch was created to re-order files related to animals (buildings, units, unsorted stuff, pedia), and if possible to fix entries here and there.

### CODE REVIEW

**Comment by raxo2222** [comment]
You can't change infotypes themselves!

Only their TXT keys.

**Comment by SannitaSSJ** [comment]
I thought I changed only the keys, not the infotypes!

**Comment by raxo2222** [comment]
Well you didn't copy whole text string.
So BUILDING_GOVENORS_MENAGERIE got replaced with BUILDING_GOVERNOR_MENAGERIE for example

**Comment by SannitaSSJ** [comment]
Ok, I'll undo that commit, and then re-try.

**Pull request merged**
