### PR TITLE
[WIP] Save Compatibility fixes

### PR DESCRIPTION
**Pull request by ghost**
**Not compatible with older saves!!!!**

### CODE REVIEW

**Comment by billw2012** [comment]
We should get this in now ASAP, is there much left to do?

**Comment by alberts2** [comment]
It's not ready.

There are some known issues left to be done and i havent even started with CvUnit which has some possible issues as well.

**Comment by Thunderbrd** [comment]
Can you give us any kind of an estimation of when you'd like to start this process of implementation?  I think we're all growing eager to get the save compat break started fairly soon so that it doesn't get ruined by other projects making it too difficult to merge in again this time.

**Comment by alberts2** [comment]
> Can you give us any kind of an estimation of when you'd like to start this process of implementation?  I think we're all growing eager to get the save compat break started fairly soon so that it doesn't get ruined by other projects making it too difficult to merge in again this time.

At my current work rate it will take another year or so.

**Comment by MattOttawa** [comment]
You gonna do a bit more on this branch Alberts2? I noticed you were around yesterday haha.
It would be perfect timing.

**Comment by alberts2** [comment]
This has to wait at least until v41 is released. Because the current svn already breaks saves and nobody want's multiple save breaking updates in a short period of time.

**Comment by raxo2222** [comment]
There are three code lines in savebreaking notes - I think those never got used here.
    // @SAVEBREAK DELETE 8/7/2018
    // Delete this code at the next save break.
    // Legacy for FreeTradeRegionBuilding. We need to write out something here to keep save compatibility, so just write out the free area building one again
    WRAPPER_WRITE_CLASS_ARRAY(wrapper, "CvCity", REMAPPED_CLASS_TYPE_BUILDINGS, GC.getNumBuildingInfos(), m_paiNumFreeAreaBuilding);
    // SAVEBREAK@

    // @SAVEBREAK REPLACE 8/7/2018
    // Update this code at the next save break.
    // We determined that the answer was not what we thought, there could be galactic consequences.
    m_fragileSaveData = 42;
    // REPLACE WITH
    // m_fragileSaveData = "towel";
    // SAVEBREAK@

    // @SAVEBREAK ADD 8/7/2018
    // Add this code at the next save break.
    // WRITE_SAVE_DATA(m_newData);
    // SAVEBREAK@

**Comment by raxo2222** [comment]
There are some savebreak notes in savebreakling notes from 2018 lol

**Comment by Toffer90** [comment]
Yeah, we didn't hear from you, so we decided to push the save breaking stuff to SVN when we did.

No worries,, the removal of unitclass and buildingclass was the main goal of this save break period.
Accomplishing that made this save break period well worth it on its own, and any other projects in this area can wait till our next save break period which I hope won't be before at least a year from now.

**Comment by MattOttawa** [comment]
Wouldn't it make sense to merge this branch now? I don't think it's too late. Player's were told saves would be broken long ago. Player's were also told saves may be broken repeatedly for a couple months. I think they'll be ok with this last thing. That'll be the second time in like a week for svn players and we'll be done. Not bad.

**Comment by Toffer90** [comment]
> Wouldn't it make sense to merge this branch now? I don't think it's too late. Player's were told saves would be broken long ago. Player's were also told saves may be broken repeatedly for a couple months. I think they'll be ok with this last thing. That'll be the second time in like a week for svn players and we'll be done. Not bad.

It would be okay if this branch was finished now, or in the next 2 days, but as far as I understand, it's a work in progress.

**Comment by alberts2** [comment]
There's alot of work left to do e.g CvUnit has a lot of save compatiblity bugs.
I'am not in a hurry to finish these unwanted bug fixes because Players really hate save breaking changes even if they fix bugs.

**Pull request closed without merging**
