### PR TITLE
Removed caching of highly used types after loading a game.

### PR DESCRIPTION
**Pull request by MattOttawa**

### CODE REVIEW

**Comment by Thunderbrd** [comment]
Just curious but wasn't this one of the most important things we had to reduce turn times?

**Comment by MattOttawa** [comment]
Probably.

**Comment by Thunderbrd** [comment]
So what is the thinking involved in removing them?

**Comment by MattOttawa** [comment]
Removed caching of highly used types after loading a game. #559

These value come from the xml. Caching them once at the start is all that's needed. Caching them again won't give different values, so it's pointless.

**Comment by Thunderbrd** [comment]
I know it seems that way, but from what I understand, it's very slow to access them.  Could be I'm wrong but it's what I've read on the forums.  Alberts2 or Bill would be able to comment further.

**Comment by alberts2** [comment]
Things like the replacement system make it possible to change anything after loading the xml. That makes it necessary to update cached stuff.

**Pull request closed without merging**
